flows:
  - name: default
    language: ruby
    version: 2.3.0

    trigger:
      push:
        - develop
        - master

    finalize:
      email:
        success:
          - gy@fir.im
          - hl@fir.im
        failure:
          - gy@fir.im

    steps:
      - name: init
        plugin:
          name: ruby_init

      - name: Git Clone
        plugin:
          name: git

      - name: Install
        plugin:
          name: ruby_install

      - name: Test
        scripts:
          - bundle exec rspec spec
